#!/usr/bin/env bash
#
# install-hooks.sh — wire post-commit and post-merge to scripts/hooks/release-check.sh.
# Run once per clone. Git hooks are not version-controlled; this re-creates them.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$(git -C "$ROOT" rev-parse --git-path hooks)"
mkdir -p "$HOOKS_DIR"

for h in post-commit post-merge; do
  [ -e "$HOOKS_DIR/$h" ] && echo "WARNING: overwriting existing $h hook"
  cat > "$HOOKS_DIR/$h" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit.
exec bash "$ROOT/scripts/hooks/release-check.sh"
EOF
  chmod +x "$HOOKS_DIR/$h"
  echo "Installed $h -> scripts/hooks/release-check.sh"
done
echo "Done. Hooks active for this clone. (Re-run after a fresh clone.)"
